all:
	nvcc -D__GPU -D__CUDA -c SDDK/GPU/fft_kernels.cu
	CC -O3 -DNDEBUG -D__GPU -D__CUDA -D__PROFILE_FUNC -fopenmp test_fft_correctness_1.cpp -I./SDDK -I./  -I/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/include/fftw/ -mkl -lcufft -lcublas -lcudart fft_kernels.o
